<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="7" failures="2" errors="0" time="2.951">
  <testsuite name="testing" errors="0" failures="1" skipped="0" timestamp="2024-05-31T11:08:54" time="0.807" tests="1">
    <testcase classname="testing gets data" name="testing gets data" time="0.062">
      <failure>SyntaxError: Unexpected end of JSON input
    at JSON.parse (&lt;anonymous&gt;)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4292:19)
    at successSteps (node:internal/deps/undici/undici:4274:27)
    at fullyReadBody (node:internal/deps/undici/undici:2695:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at consumeBody (node:internal/deps/undici/undici:4283:7)
    at Object.&lt;anonymous&gt; (D:\VsCodeProjects\PrivateAPiTestProject\test\genericApi.test.ts:14:21)</failure>
    </testcase>
  </testsuite>
  <testsuite name="Confirm that normal results are returned when a fixed Field is specified." errors="0" failures="0" skipped="0" timestamp="2024-05-31T11:08:54" time="2.302" tests="1">
    <testcase classname="Confirm that normal results are returned when a fixed Field is specified. Confirm that a normal result is returned in case of P_Id" name="Confirm that normal results are returned when a fixed Field is specified. Confirm that a normal result is returned in case of P_Id" time="0.047">
    </testcase>
  </testsuite>
  <testsuite name="Confirm that normal results are returned when a fixed Field is specified." errors="0" failures="0" skipped="0" timestamp="2024-05-31T11:08:54" time="2.302" tests="1">
    <testcase classname="Confirm that normal results are returned when a fixed Field is specified. Confirm that a normal result is returned in case of P_Id" name="Confirm that normal results are returned when a fixed Field is specified. Confirm that a normal result is returned in case of P_Id" time="0.05">
    </testcase>
  </testsuite>
  <testsuite name="testing" errors="0" failures="1" skipped="0" timestamp="2024-05-31T11:08:54" time="2.34" tests="1">
    <testcase classname="testing gets data" name="testing gets data" time="0.049">
      <failure>SyntaxError: Unexpected end of JSON input
    at JSON.parse (&lt;anonymous&gt;)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4292:19)
    at successSteps (node:internal/deps/undici/undici:4274:27)
    at fullyReadBody (node:internal/deps/undici/undici:2695:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at consumeBody (node:internal/deps/undici/undici:4283:7)
    at Object.&lt;anonymous&gt; (D:\VsCodeProjects\PrivateAPiTestProject\test\genericApi.test.ts:14:21)</failure>
    </testcase>
  </testsuite>
  <testsuite name="JSON validation" errors="0" failures="0" skipped="0" timestamp="2024-05-31T11:08:54" time="2.341" tests="2">
    <testcase classname="JSON validation should validate correct JSON data" name="JSON validation should validate correct JSON data" time="0.003">
    </testcase>
    <testcase classname="JSON validation should invalidate incorrect JSON data" name="JSON validation should invalidate incorrect JSON data" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="PrivateAPI Generic resource record test case - 1" errors="0" failures="0" skipped="0" timestamp="2024-05-31T11:08:54" time="2.355" tests="1">
    <testcase classname="PrivateAPI Generic resource record test case - 1 Confirm that a normal result is returned in case of Generic Resource id : 3 Field id : Job.P_Id,Job.P_Position ID List : 10001" name="PrivateAPI Generic resource record test case - 1 Confirm that a normal result is returned in case of Generic Resource id : 3 Field id : Job.P_Id,Job.P_Position ID List : 10001" time="0.045">
    </testcase>
  </testsuite>
</testsuites>